import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./(context)/appContextProvider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="emerald">
      <SessionProvider>
        <AppContextProvider>
          <body className={montserrat.className}>{children}</body>
        </AppContextProvider>
      </SessionProvider>
    </html>
  );
}
