export enum Placeholders {
  ENTER_NAME = "Enter a name.",
  ENTER_TESTIMONIAL_TITLE = "Enter a title for testimonial",
  ENTER_YOUR_THOUGHTS = "Please enter your thoughts.",
  ENTER_YOUR_EMAIL = "Enter your email",
  ENTER_YOUR_FNAME = "Enter first name",
  ENTER_YOUR_LNAME = "Enter last name",
  ADD_QUE = "Add your custom question here and click add",
  SHARE_PERMISSION = "Share this form with others",
  PICK_A_BOARD = "Pick boards for testimonial",
  PICK_A_TAG = "Pick tags for testimonial",
  PICK_A_COLOR = "Pick a color",
  PICK_H_FONT = "Pick heading font",
  PICK_P_FONT = "Pick text font",
  PICK_A_THEME = "Pick a theme",
  PICK_H_FONT_SIZE = "Pick heading font size",
  PICK_P_FONT_SIZE = "Pick text font size",
  BORDER_RADIUS = "Select border radius.",
  BG_COLOR = "Select background color.",
}
